---
version: '3.5'
services:    
    oauth2proxy:
        # internal: oauth2proxy on port 4180
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        environment:
            OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
            OAUTH2_PROXY_HTTPS_ADDRESS: '0.0.0.0:8080'
            OAUTH2_PROXY_COOKIE_SECRET: ${SECRET_KEY}
            OAUTH2_PROXY_COOKIE_DOMAINS: '127.0.0.1' # Required so cookie can be read on all subdomains.
            OAUTH2_PROXY_WHITELIST_DOMAINS: '*' # Required to allow redirection back to original requested target.
            OAUTH2_PROXY_PROVIDER: 'google'
            OAUTH2_PROXY_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            OAUTH2_PROXY_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            OAUTH2_PROXY_EMAIL_DOMAINS: '*'
            OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://127.0.0.1:8080'
            OAUTH2_PROXY_REDIRECT_URL: 'https://127.0.0.1:8080/oauth2/callback'
            OAUTH2_PROXY_UPSTREAMS: 'http://headers-printer:5000'
            OAUTH2_PROXY_PREFER_EMAIL_TO_USER: 'true'
            OAUTH2_PROXY_TLS_CERT_FILE: '/ssl/cert.pem'
            OAUTH2_PROXY_TLS_KEY_FILE: '/ssl/key.pem'
            OAUTH2_PROXY_REVERSE_PROXY: 'false'
            OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: 'false'
        ports:
          - "127.0.0.1:4180:4180"
          - "127.0.0.1:8080:8080"
        volumes:
          - /ssl:/ssl
        links:
          - headers-printer

    headers-printer:
        image: localhost/headers-printer:latest
        build: .
        ports:
          - "5000:5000"
